CONFIG/urls.py
from pipes import Template
from django.contrib import admin
from django.urls import path, include
from institute_dashaboard import views
from django.conf import settings
from django.conf.urls.static import static
from Core.views import IndexView, SignupView, LoginView
from django.views.generic import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='homepage'),
    path('notice_board/', views.notice_board, name='notice_board'),
    # path('students_info/', views.students_info, name='students_info'),
    path('students_info/', views.StudentsInfoView.as_view(), name='students_info'),
    path('<int:id>/', views.students_details, name='students_details'),
    path('result/', views.result, name='result'),
    path('addmission/', views.OnlineAdmissionView.as_view(), name='onlineadm'),
    path('complain/', views.complain, name='complain'),
    path('contact/', views.contact_page, name='contact'),
    path('gallery/', views.gallery_page, name='gallery'),
    path('teachers_info/', views.teachers_page, name='teachers_info'),
    path('other_employee/', views.stafs_page, name='staf'),
    path('cultural_program/', views.cultur, name='cultur'),
    path('sports/', views.sports, name='sports'),
    path('speach/', views.speach, name='speach'),
    path('lokko_uddessho/', views.lokkouddessho, name='lokko'),
    path('history/', views.clg_history, name='history'),
    path('news/', views.newspage, name='news'),
    path('news/', views.newspage, name='news'),
    path('student/', include('students.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('auth/signup/', SignupView.as_view(), name='signup'),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('prms', include('django_prometheus.urls')),
    path('customize/', include('websitesetting.urls')),
    path('dashboard_management/', include('dashboard_management.urls')),
    

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Core/urls.py
"""Core > urls.py"""
# DJANGO URLS
from django.urls import path
# CORE IMPORTS
from Core import views

app_name = 'core'

urlpatterns = [
    # index url ---------------------------------------------------------------
    path('', views.IndexView.as_view(), name='index'),

    # user --------------------------------------------------------------------
    path(
        'users/', views.UserListView.as_view(), name='users'
    ),
    path(
        'user/create/', views.UserCreateView.as_view(), name='user_create'
    ),
    path(
        'user/detail/<int:pk>',
        views.UserDetailView.as_view(),
        name='user_detail'
    ),
    path(
        'user/update/<int:pk>',
        views.UserUpdateView.as_view(),
        name='user_update'
    ),
]

dashboard_management/urls.py
from django.urls import path
from dashboard_management import views

app_name = 'dashboard_management'

urlpatterns = [

    # students info
    path(
        'onlineadmission/',
        views.OnlineAdmissionProcess.as_view(),
        name='online_admission'
    ),
    path(
        'portelmanager/dashboard',
        views.PortalManagerDashboard.as_view(),
        name='portal_manager_board'
    ),
    path(
        'assigned/class',
        views.AssignClassesToTeacher.as_view(),
        name='assigned_class_teacher'
    ),
    path(
        'notice/adding',
        views.ADDNotice.as_view(),
        name='notice_adding'
    ),
    path('delete-notice/<int:notice_id>/',
         views.DeleteNotice.as_view(),
         name='delete_notice'),
    path(
        'news/adding',
        views.AddNews.as_view(),
        name='news_adding'
    ),
    path('delete-news/<int:news_id>/',
         views.DeleteNews.as_view(),
         name='delete_news'),

    path('galleries/', views.GalleryView.as_view(), name='gallery_list'),
    path('galleries/add/', views.GalleryView.as_view(), name='add_gallery'),
    path('galleries/edit/<int:gallery_id>/', views.GalleryView.as_view(), name='edit_gallery'),
    path('galleries/delete/<int:gallery_id>/', views.GalleryView.as_view(), name='delete_gallery'),
    
    path('add/teacher',
         views.AddTeacherView.as_view(),
         name='add_teacher'
        ),
    path('add/stuff',
         views.AddStuff.as_view(),
         name='add_stuff'
        ),


]

students/urls.py
from django.urls import path
from students import views

app_name = 'students'

urlpatterns = [

    # students info
    path(
        'dashboard/',
        views.SDashboard.as_view(),
        name='dashobard_app'
    ),
    path(
        'result/dashboard/',
        views.ResultsDashboard.as_view(),
        name='result_dashobard'
    ),
    path(
        'studentsportal/',
        views.StudentsDashboard.as_view(),
        name='students_dashobard'
    ),
    path(
        'create',
        views.StudentsCreateView.as_view(),
        name='students_create'
    ),
    path(
        'list',
        views.StudentsListView.as_view(),
        name='students_list'
    ),
    path(
        'search/add/result',
        views.ListOfResultsAddView.as_view(),
        name='students_list_for_result'
    ),
    path( 
        '<int:exm_tp>/search/<int:clas_nm>/add/<int:sub>/<int:clas_yr>/result/<int:ecm_yr>/<int:clas_sec>/list',
        views.ListOfResultscCeateResultView.as_view(),
        name='students_list_for_result_add'
    ),
    path(
        'show/result/list',
        views.ShowResultView.as_view(),
        name='show_result'
    ),
    path(
        'show/<int:pk>/<int:sem>/result',
        views.SemesterResultView.as_view(),
        name='show_result_detail'
    ),
    path(
        'show/<int:pk>/<int:sem>/result/pdf',
        views.SemesterResultViews.as_view(),
        name='show_result_detail_pdf'
    ),
    path(
        'info',
        views.StudentsInfoDashboard.as_view(),
        name='std_info_dashboard'
    ),
    path(
        'result/<int:stdn>/<int:subj>/create',
        views.ResultsCreateView.as_view(),
        name='result_create'
    ),
    path(
        'subjects/<int:stu_id>/',
        views.StudentsSubjects.as_view(),
        name='students_subjects'
    ),
    path(
        'routine/',
        views.StudentsRoutine.as_view(),
        name='students_routine'
    ),
    path(
        'register/<int:stu_id>/class',
        views.StudentsClassRegister.as_view(),
        name='students_class_register'
    ),
    path(
        'my/result',
        views.StudentsResultSpecific.as_view(),
        name='students_specific_result'
    ),
]

students/models/class_studn.py
from django.db import models
from .commonfields import CommonFields
from django.utils.translation import gettext_lazy as _
from .subject import Subjects


class ClassName(CommonFields):
    name = models.CharField(
        _("Name"), max_length=255, null=True
    )
    code = models.CharField(
        _("Code"), max_length=255, null=True
    )
    class_nm = models.ForeignKey(
        'ClassYear', on_delete = models.SET_NULL, null=True,
        verbose_name="Class Year", related_name="cls_yr"
    )


    def __str__(self):
        return self.name


class ClassYear(CommonFields):
    class_year = models.CharField(
        _("Class Year"), max_length=15, null=True
    )
    # date = models.DateField(
    #     _("Date of Exam"), null=True
    # )
    def __str__(self):
        return self.class_year

class SectionClas(CommonFields):
    class_nm = models.ForeignKey(
        ClassName, on_delete = models.SET_NULL, null=True,
        verbose_name="Class Name", related_name="cls_nm"
    )
    name = models.CharField(
        _("Name"), max_length=255, null=True
    )
    code = models.CharField(
        _("Code"), max_length=255, null=True
    )
    def __str__(self):
        return self.name


class Session(CommonFields):
    name = models.CharField(
        _("Name"), max_length=255, null=True
    )

    def __str__(self):
        return self.name

students/models/subject.py
from django.db import models
from .commonfields import CommonFields
# from .class_studn import ClassName
from django.utils.translation import gettext_lazy as _

class Subjects(CommonFields):

    name = models.CharField(
        _("Name"), max_length=255, null=True
    )
    code = models.CharField(
        _("Code"), max_length=255, null=True
    )
    class_nm = models.ForeignKey(
        'ClassName', on_delete = models.SET_NULL, null=True,
        verbose_name="Class Names", related_name="clss_nme"
    )
    def __str__(self):
        return self.name

students/forms/result_input.py
from django import forms
from students.models.result import ResultInfo
from students.models.class_studn import ClassYear, ClassName


class ResultInputForm(forms.ModelForm):
    class Meta:
        model = ResultInfo
        fields = [
            # 'marks',
            # 'exam_type',
            # 'exam_year',

        ]

class AddResultstdlist(forms.ModelForm):
    class Meta:
        model = ResultInfo
        fields = [
            'exam_type',
            'exam_year',
            'class_name',
            'subject',
            'section',
        ]

class ClasYearForm(forms.ModelForm):
    class Meta:
        model = ClassName
        fields = [
            'class_nm',
        ]

students/forms/studentscreateform.py
from django import forms
from students.models.students_info import StudentsInfo

class StudentsInfoForm(forms.ModelForm):
    class Meta:
        model = StudentsInfo
        fields = (
            'name',
            'unique_roll',
            'father_name',
            'mother_name',
            'students_image',
            'date_of_birth',
            'present_address',
            'permanent_address',
            'personal_mobile_number',
            'gurdian_mobile_number',
            'admission_date',
            'gender',
            'class_name',
            'section_class',
        )

students/views/create_students.py
from django.views.generic import (
    ListView, CreateView, UpdateView, DetailView, View
)
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import (
    LoginRequiredMixin, UserPassesTestMixin,
    PermissionRequiredMixin
)
import calendar
from django.contrib.auth.models import Group
from datetime import datetime
from students.models.students_info import StudentsInfo
from students.forms.studentscreateform import StudentsInfoForm
from students.forms.result_input import ResultInputForm
from Core.models import UserManager, User

# prfx = self.subscription
#             # print(prfx, prfx.subs_type, prfx.subs_type.prefixs, 'shdddd')
#             start_from = 1
#             i = generate_account_no(self.account_no, start_from, prfx.subs_type.prefixs) # noqa
#             while Accounts.objects.filter(account_no=i).exists():
#                 start_from += 1  # increment if id exists
#                 i = generate_account_no(self.account_no, start_from, prfx.subs_type.prefixs) # noqa
#             self.account_no = i

def generate_user_id(prefix):
    current_year = datetime.now().year  # get current year
    current_year = str(current_year)
    cu_first_two = current_year[:2]
    cu_last_two = datetime.now().strftime("%y")
    current_date = datetime.today()
    _, num_weeks = calendar.monthrange(current_date.year, current_date.month)
    week_number = (current_date.day - 1) // 7 + 1
    if current_date.day + 7 - (week_number - 1) * 7 > num_weeks * 7:
        week_number = num_weeks
    current_month = str(datetime.now().month)  # get current month
    if len(current_month) == 1:
        month = '0' + current_month
    else:
        current_month = current_month
    # count of data
    last_add = User.objects.values('user_id').last()
    # print(last_add, 'add-------')
    total_account = str(
        User.objects.values('user_id').count() + 1
    )
    # print(total_account, 'total-------------')
    if len(total_account) == 1:
        last_id = f'0000{total_account}'
    elif len(total_account) == 2:
        last_id = f'000{total_account}'
    elif len(total_account) == 3:
        last_id = f'00{total_account}'
    else:
        last_id = total_account
    # current_week_of_this_month
    user_id_no = f'{cu_last_two}{month}{week_number}{last_id}' # noqa
        # user_id_no = f'{prefix}{cu_last_two}00{cu_first_two}{month}{week_number}{last_id}' # noq
    return user_id_no


class StudentsCreateView(
    LoginRequiredMixin, UserPassesTestMixin,
    PermissionRequiredMixin, CreateView
):

    model = StudentsInfo
    form_class = StudentsInfoForm
    permission_required = 'students.add_studentsinfo'
    template_name = 'studentsinfo/students_info_create.html'
    success_url = reverse_lazy('students:students_list')

    def test_func(self):
        return self.request.user.is_active

    def get(self, request, *args, **kwargs):
        form_class = StudentsInfoForm
        group = Group.objects.all()
        context = {
            'form': form_class,
            'group': group
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = StudentsInfoForm(request.POST, request.FILES)
        user_manager = UserManager
        # print(form, 'form-----------------------')
        if form.is_valid():
            student_info_ins = form.save(commit=False)
            if student_info_ins.unique_roll:
                user = user_manager.create_user(
                    self=UserManager,
                    user_id=str(student_info_ins.unique_roll),
                    password=str(student_info_ins.personal_mobile_number),
                )
            else:
                user_id = generate_user_id(prefix=student_info_ins.section_class)
                # print(user_id, 'id------------------------')
                user = user_manager.create_user(
                    self=UserManager,
                    user_id=str(user_id),
                    password=str(student_info_ins.personal_mobile_number),
                )
                student_info_ins.unique_roll = user_id
            student_info_ins.save()
            print(user,)
            group = Group.objects.get(id=1)
            group.user_set.add(user)
            # user.groups.add(group)
            print(group, 'group')
        else:
            print(form.errors, 'Student Create Error')
        return redirect('students:students_list')



class StudentsListView(
    LoginRequiredMixin, UserPassesTestMixin,
    PermissionRequiredMixin, View
):

    model = StudentsInfo
    permission_required = 'students.view_studentsinfo'
    template_name = 'studentsinfo/students_list.html'

    def test_func(self):
        return self.request.user.is_active
    
    def get(self, request):
        stdn = self.model.objects.all().order_by('-id')
        # print(stdn, 'aa')
        # studentss = StudentsInfo.objects.get(id=1)
        # print(studentss)
        form = ResultInputForm()
        context = {
            'object_list': stdn,
            'form': form
        }
        return render(request, self.template_name, context)
    
    def post(self, request):
        form = ResultInputForm(request.POST)
        markes = []
        for mark in request.POST.getlist('mark'):
            markes.append(mark)
        i=0
        for single_mark in markes:
            for student in request.POST.getlist('sid'):
                students = StudentsInfo.objects.get(id=student)
                a = markes[i]
                i += 1
                print(a, '----')
                print(students, 'ddd---dd')
                
                # V_insert_data.save()
        #             if form.is_valid():
        #     print('d')
        # else:
                # V_insert_data = studentsEnrolledSubjectsGrade(
                # Teacher=teacher,
                # Students_Enrollment_Records=students,
                # Date=single_date,
                # Grade=markes[i]
                # )
        #     print('error')
            return render(request, self.template_name)

students/views/dashboard.py
from django.shortcuts import render
from django.views.generic import (
    ListView, CreateView, UpdateView, DetailView, TemplateView
)
from students.models import StudentsInfo
from django.urls import reverse_lazy
from django.contrib.auth.mixins import (
    LoginRequiredMixin, UserPassesTestMixin,
    PermissionRequiredMixin
)



class SDashboard(
    LoginRequiredMixin, UserPassesTestMixin,
    # PermissionRequiredMixin, 
    TemplateView
):
    template_name = 'studentsinfo/dashobard.html'
    # permission_required = 'students.view_students'

    def test_func(self):
        return self.request.user.is_active
    

class StudentsInfoDashboard(
    LoginRequiredMixin, UserPassesTestMixin,
    PermissionRequiredMixin, TemplateView
):
    template_name = 'studentsinfo/stdn_info_dashboard.html'
    permission_required = 'students.view_students'

    def test_func(self):
        return self.request.user.is_active

    def get(self, request, *args, **kwargs):
        students_count = StudentsInfo.objects.values_list('id').count()
        # print(students_count, 'total studernts------------------------')
        context = {
            'total_students_count':students_count,
        }
        return self.render_to_response(context)


class ResultsDashboard(
    LoginRequiredMixin, UserPassesTestMixin,
    PermissionRequiredMixin, TemplateView
):
    template_name = 'result/result_dashboard.html'
    permission_required = 'students.view_students'

    def test_func(self):
        return self.request.user.is_active


class StudentsDashboard(
    LoginRequiredMixin, UserPassesTestMixin,
    # PermissionRequiredMixin, 
    TemplateView
):
    template_name = 'studentsinfo/students_dashboard.html'
    permission_required = 'students.view_students'

    def test_func(self):
        return self.request.user.is_active

students/templates/result/add_result_list.html
{% extends 'institute/base.html' %} 
{% load static %} 
{% load widget_tweaks %}
{% block title %}
<title>Students Result add</title>
{% endblock title %} 

<!-- left side main things start from here -->
{% block leftside %} 

      <!-- student short info start -->
<div class="row">
    <div class="container-fluid">
    <div class="container-fluid">
      <div class="bg-success pt-3 ps-2 pb-1 ">
        <h5 class="text-white bangla">Add Result</h5>
      </div>
      <div class="bg-light border mt-1 py-2 bangla">

        <div class="table_scroll">
            <table class="table table-hove table-bordered my-0">
                <thead>
                    <tr>
                        <th>SL.No.</th>
                        <th>Image</th>
                        <th>Name</th>
                        <th>Roll</th>
                        <th>Class</th>
                        <th>Year</th>
                        <th>Result{{object_lis}}</th>
                        {% comment %} <th style="width: 21%">Actions</th> {% endcomment %}
                    </tr>
                </thead>
            <tbody>
                {% for object in object_list %}
                <tr>
                    <td class="text-center">
                    {% if page_obj %}
                    {{ forloop.counter0|add:page_obj.start_index }}
                    {% else %}
                    {{ forloop.counter }}
                    {% endif %}
                    
                    <td> Image{{object_lis}}</td>
                    <td> {{object.name}} </td>
                    <td> {{object.unique_roll}} </td>
                    <td> {{object.class_name}} </td>
                    <td> 2023</td>
                    <form action="" method="post">
                      {% csrf_token %}
                    {% comment %} <td> {{form.marks}}</td> {% endcomment %}
                    <td> <input width="5%" name="mark" class="form-control" placeholder="input result here" type="text"> </td>
                    <td> <input name="sid" value="{{object.id}}" type="hidden"> </td>

                    
                
                {% comment %} {% comment %} <td>{{object.lines.item}}</td>
                <td>{{object.lines.amount}}</td>
                <td>{% if object.date %}{{ object.date }}{% endif %}</td>
                <td>{% if object.description %}{{ object.description|truncatewords:4 }}{% endif %}</td>
                 {% endcomment %}
                 {% comment %} <td><a class="btn btn-success btn-sm" href="#"><i class="fa-solid fa-pen-to-square"></i>Edit</a>  
                    <a class="btn btn-primary btn-sm" href=""><i class="fa fa-pencil-square-o" aria-hidden="true"></i>Delete</a>
                    <a class="btn btn-primary btn-sm" href="{% url 'students:result_create' object.id 1 %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>Add Result</a></td>   {% endcomment %}

            </tr>
            {% endfor %}
            </tbody>
        </table>
      </div>
      {% comment %} <div> {% endcomment %}
        {% comment %} {% include 'snippets/pagination.html' %} {% endcomment %}
        
        <input class="btn btn-primary" type="submit" value="Submit Result">
      </form>
   

    
            

            <!-- students info table by search end here -->
                <!-- student short info end -->
               

          
     

 
          <!-- Notice Table non-search end here -->
          
         <!-- Pagination starting start here -->
         
          <!-- Pagination end here -->
          
          <!-- Page Number show starting here -->
          
        <!-- Page Number show end here -->
        
        
      </div>
    </div>
  </div>
  {% endblock leftside %}
  {% block rightside %}

  {% endblock rightside %}

students/templates/result/result_dashboard.html
{% extends 'institute/base.html' %} 
{% load static %} 
{% load widget_tweaks %}
{% block title %}
<title>Students Info Dashboard</title>
{% endblock title %} 

<!-- left side main things start from here -->
{% block leftside %} 
<style>
    body{
        margin-top:20px;
        background:#FAFAFA;
    }
    .order-card {
        color: #fff;
    }
    
    .bg-c-blue {
        background: linear-gradient(45deg,#4099ff,#73b4ff);
    }
    
    .bg-c-green {
        background: linear-gradient(45deg,#2ed8b6,#59e0c5);
    }
    
    .bg-c-yellow {
        background: linear-gradient(45deg,#FFB64D,#ffcb80);
    }
    
    .bg-c-pink {
        background: linear-gradient(45deg,#FF5370,#ff869a);
    }
    
    
    .card {
        border-radius: 5px;
        -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);
        box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);
        border: none;
        margin-bottom: 30px;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out;
    }
    
    .card .card-block {
        padding: 25px;
    }
    
    .order-card i {
        font-size: 26px;
    }
    
    .f-left {
        float: left;
    }
    
    .f-right {
        float: right;
    }
</style>

<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" rel="stylesheet">
<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <p class="alert bg-success text-light text-center">Dashboard</p>
            <div class="card-body">
    <div class="row">
        <div class="col-md-4 col-xl-3">
            <a style="text-decoration:none"  href="{% url 'students:students_list_for_result' %}"> 
                <div class="card bg-c-blue order-card">
                    <div class="card-block">
                        <h6 class="m-b-20">AR</h6>
                        <h4 class="text-right">Add Result</span></h4>
                        <p class="m-b-0">-</span></p>
                    </div>
                </div>
            </a>
        </div>
        
        <div class="col-md-4 col-xl-3">
            <a style="text-decoration:none"  href="{% url 'students:show_result' %}"> 
            <div class="card bg-c-green order-card">
                <div class="card-block">
                    <h6 class="m-b-20">EWR</h6>
                    <h4 class="text-right">Exam wise Result</h4>
                    <p class="m-b-0">-</span></p>
                </div>
            </div>
            </a>
        </div>
        
        <div class="col-md-4 col-xl-3">
            <a style="text-decoration:none"  href="{% url 'students_info' %}"> 
            <div class="card bg-c-yellow order-card">
                <div class="card-block">
                    <h6 class="m-b-20">SS</h6>
                    <h4 class="text-right">Search Students</h4>
                    <p class="m-b-0">-</span></p>
                </div>
            </div>
        </a>
        </div>
        
        <div class="col-md-4 col-xl-3">
            <a style="text-decoration:none"  href="{% url 'dashboard_management:assigned_class_teacher' %}"> 
            <div class="card bg-c-pink order-card">
                <div class="card-block">
                    <h6 class="m-b-20">AC</h6>
                    <h4 class="text-right">Assigned Classes</h4>
                    <p class="m-b-0">-</span></p>
                </div>
            </div>
        </a>
        </div>
        
        {% comment %} <div class="col-md-4 col-xl-3">
            <div class="card bg-c-pink order-card">
                <div class="card-block">
                    <h6 class="m-b-20">Result</h6>
                    <h2 class="text-right"><i class="fa-solid fa-screen-users"></i><span>486</span></h2>
                    <p class="m-b-0">Total<span class="f-right">351</span></p>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-xl-3">
            <div class="card bg-c-pink order-card">
                <div class="card-block">
                    <h6 class="m-b-20">Result</h6>
                    <h2 class="text-right"><i class="fa-solid fa-screen-users"></i><span>486</span></h2>
                    <p class="m-b-0">Total<span class="f-right">351</span></p>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-xl-3">
            <div class="card bg-c-pink order-card">
                <div class="card-block">
                    <h6 class="m-b-20">Result</h6>
                    <h2 class="text-right"><i class="fa-solid fa-screen-users"></i><span>486</span></h2>
                    <p class="m-b-0">Total<span class="f-right">351</span></p>
                </div>
            </div> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
	</div>
</div>
{% endblock leftside %}
{% block rightside %}

{% endblock rightside %}

students/templates/result/show_result_list.html
{% extends 'institute/base.html' %} 
{% load static %} 
{% load widget_tweaks %}
{% block title %}
<title>Students List</title>
{% endblock title %} 

<!-- left side main things start from here -->
{% block leftside %} 

      <!-- student short info start -->
<div class="row">
    <div class="container-fluid">
    <div class="container-fluid">
      <div class="bg-success pt-3 ps-2 pb-1 ">
        <h5 class="text-white bangla">All Students List</h5>
      </div>
      <div class="bg-light border mt-1 py-2 bangla">

        <div class="table_scroll">
            <table class="table table-hove table-bordered my-0">
                <thead>
                    <tr>
                        <th>SL.No.</th>
                        <th>Image</th>
                        <th>Name</th>
                        <th>Roll</th>
                        <th>Class</th>
                        <th>Year</th>
                        {% comment %} <th>Result{{object_lis}}</th> {% endcomment %}
                        <th >Semester</th>
                    </tr>
                </thead>
            <tbody>
              <form action="" method="post">
                {% csrf_token %}
            {% for object in object_list %}
            <tr>
                <td class="text-center">
                    {% if page_obj %}
                    {{ forloop.counter0|add:page_obj.start_index }}
                    {% else %}
                    {{ forloop.counter }}
                    {% endif %}
                    
                    {% comment %} <td> <img src="{% url 'object.students_image' %}" width="50px" alt="img"></td> {% endcomment %}
                    <td> image comming soon </td>
                    <td> {{object.name}} </td>
                    <td> {{object.unique_roll}} </td>
                    <td> {{object.class_name}} </td>
                    <td> {{object.admission_date}} </td>
                                      {% comment %} <td> {{form.marks}}</td> {% endcomment %}
                    {% comment %} <td> <input name="mark" type="text"> </td>
                    <td> <input name="sid" value="{{object.id}}" type="text"> </td> {% endcomment %}

                    
                
                {% comment %} {% comment %} <td>{{object.lines.item}}</td>
                <td>{{object.lines.amount}}</td>
                <td>{% if object.date %}{{ object.date }}{% endif %}</td>
                <td>{% if object.description %}{{ object.description|truncatewords:4 }}{% endif %}</td>
                 {% endcomment %}
        <td><a class="btn btn-primary btn-sm" href="{% url 'students:show_result_detail' object.id 1 %}"></i> 1st Semester</a> 
                    <td> <a class="btn btn-primary btn-sm" href="#"></i> 2nd Semester</a>  </td>
                    <td>  <a class="btn btn-primary btn-sm" href="#"></i> 3rd Semester</a> </td> 
                    {% comment %} <a class="btn btn-primary btn-sm" href="#"></i> 2nd Semester Result</a>  
                    <a class="btn btn-primary btn-sm" href="#"></i> 3rd Semester Result</a>   {% endcomment %}
                 </td>
                    {% comment %} <a class="btn btn-danger btn-sm" href=""><i class="bi bi-trash"></i> Delete</a> {% endcomment %}
                    {% comment %} <a class="btn btn-primary btn-sm" href="{% url 'students:result_create' object.id 1 %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>Add Result</a></td>   {% endcomment %}

            </tr>
            {% endfor %}
            </tbody>
        </table>
      </div>
      {% comment %} <div> {% endcomment %}
        {% comment %} {% include 'snippets/pagination.html' %} {% endcomment %}
      
      </form>
   

    
            

            <!-- students info table by search end here -->
                <!-- student short info end -->
               

          
     

 
          <!-- Notice Table non-search end here -->
          
         <!-- Pagination starting start here -->
         
          <!-- Pagination end here -->
          
          <!-- Page Number show starting here -->
          
        <!-- Page Number show end here -->
        
        
      </div>
    </div>
  </div>
  {% endblock leftside %}
  {% block rightside %}

  {% endblock rightside %}