CONFIG/urls.py
from pipes import Template
from django.contrib import admin
from django.urls import path, include
from institute_dashaboard import views
from django.conf import settings
from django.conf.urls.static import static
from Core.views import IndexView, SignupView, LoginView
from django.views.generic import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='homepage'),
    path('notice_board/', views.notice_board, name='notice_board'),
    # path('students_info/', views.students_info, name='students_info'),
    path('students_info/', views.StudentsInfoView.as_view(), name='students_info'),
    path('<int:id>/', views.students_details, name='students_details'),
    path('result/', views.result, name='result'),
    path('addmission/', views.OnlineAdmissionView.as_view(), name='onlineadm'),
    path('complain/', views.complain, name='complain'),
    path('contact/', views.contact_page, name='contact'),
    path('gallery/', views.gallery_page, name='gallery'),
    path('teachers_info/', views.teachers_page, name='teachers_info'),
    path('other_employee/', views.stafs_page, name='staf'),
    path('cultural_program/', views.cultur, name='cultur'),
    path('sports/', views.sports, name='sports'),
    path('speach/', views.speach, name='speach'),
    path('lokko_uddessho/', views.lokkouddessho, name='lokko'),
    path('history/', views.clg_history, name='history'),
    path('news/', views.newspage, name='news'),
    path('news/', views.newspage, name='news'),
    path('student/', include('students.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('auth/signup/', SignupView.as_view(), name='signup'),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('prms', include('django_prometheus.urls')),
    path('customize/', include('websitesetting.urls')),
    path('dashboard_management/', include('dashboard_management.urls')),
    

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Core/urls.py
"""Core > urls.py"""
# DJANGO URLS
from django.urls import path
# CORE IMPORTS
from Core import views

app_name = 'core'

urlpatterns = [
    # index url ---------------------------------------------------------------
    path('', views.IndexView.as_view(), name='index'),

    # user --------------------------------------------------------------------
    path(
        'users/', views.UserListView.as_view(), name='users'
    ),
    path(
        'user/create/', views.UserCreateView.as_view(), name='user_create'
    ),
    path(
        'user/detail/<int:pk>',
        views.UserDetailView.as_view(),
        name='user_detail'
    ),
    path(
        'user/update/<int:pk>',
        views.UserUpdateView.as_view(),
        name='user_update'
    ),
]

dashboard_management/urls.py
from django.urls import path
from dashboard_management import views

app_name = 'dashboard_management'

urlpatterns = [

    # students info
    path(
        'onlineadmission/',
        views.OnlineAdmissionProcess.as_view(),
        name='online_admission'
    ),
    path(
        'portelmanager/dashboard',
        views.PortalManagerDashboard.as_view(),
        name='portal_manager_board'
    ),
    path(
        'assigned/class',
        views.AssignClassesToTeacher.as_view(),
        name='assigned_class_teacher'
    ),
    path(
        'notice/adding',
        views.ADDNotice.as_view(),
        name='notice_adding'
    ),
    path('delete-notice/<int:notice_id>/',
         views.DeleteNotice.as_view(),
         name='delete_notice'),
    path(
        'news/adding',
        views.AddNews.as_view(),
        name='news_adding'
    ),
    path('delete-news/<int:news_id>/',
         views.DeleteNews.as_view(),
         name='delete_news'),

    path('galleries/', views.GalleryView.as_view(), name='gallery_list'),
    path('galleries/add/', views.GalleryView.as_view(), name='add_gallery'),
    path('galleries/edit/<int:gallery_id>/', views.GalleryView.as_view(), name='edit_gallery'),
    path('galleries/delete/<int:gallery_id>/', views.GalleryView.as_view(), name='delete_gallery'),
    
    path('add/teacher',
         views.AddTeacherView.as_view(),
         name='add_teacher'
        ),
    path('add/stuff',
         views.AddStuff.as_view(),
         name='add_stuff'
        ),


]

dashboard_management/models.py
from django.db import models

# Create your models here.

dashboard_management/forms/gallery.py
# forms.py
from django import forms
from institute_dashaboard.models import (
    Gallery, complain, Notice_board, News_headline
)

class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = ['title', 'gallery_photo']

dashboard_management/forms/notice.py
from django import forms
from institute_dashaboard.models import (
    OnlineAdmission, complain, Notice_board, News_headline
)

class NoticeBoardForm(forms.ModelForm):
    class Meta:
        model = Notice_board
        fields = ['title', 'img_or_pdf', 'notice_published_date', 'url_link']

class NewsdForm(forms.ModelForm):
    class Meta:
        model = News_headline
        fields = ['title', 'img_or_pdf', 'notice_published_date', 'url_link']

dashboard_management/forms/teacher.py
# forms.py
from django import forms
from institute_dashaboard.models import Teachers_Information, Other_Employee_Information

class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teachers_Information
        fields = ['teachers_name', 'phone_number', 'email', 'designation', 'teachers_photo']
        widgets = {
            'teachers_name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'designation': forms.TextInput(attrs={'class': 'form-control'}),
            'teachers_photo': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        }


class StuffForm(forms.ModelForm):
    class Meta:
        model = Other_Employee_Information
        fields = ['Others_name', 'phone_number', 'email', 'designation', 'Others_photo']
        widgets = {
            'Others_name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'designation': forms.TextInput(attrs={'class': 'form-control'}),
            'Others_photo': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        }

dashboard_management/views/admission_dashboard.py
from django.shortcuts import render
from django.views.generic import (
    ListView, CreateView, UpdateView, DetailView, TemplateView, View
)
from students.models import StudentsInfo
from institute_dashaboard.models import OnlineAdmission, complain
from django.urls import reverse_lazy
from django.contrib.auth.mixins import (
    LoginRequiredMixin, UserPassesTestMixin,
    PermissionRequiredMixin
)


class OnlineAdmissionProcess(
    LoginRequiredMixin, UserPassesTestMixin,
    PermissionRequiredMixin, View
):
    model = OnlineAdmission
    template_name = 'online_admission.html'
    permission_required = 'dashboard_management.view_students'

    def test_func(self):
        return self.request.user.is_active

    def get(self, request, *args, **kwargs):
        online_admission_apply_count = OnlineAdmission.objects.filter(
            is_active=True
        )
        context = {
            'online_admission_apply':online_admission_apply_count,
        }
        return render(request, self.template_name, context)

dashboard_management/views/assigned_classes.py
from django.shortcuts import render
from django.views.generic import (
    ListView, CreateView, UpdateView, DetailView, TemplateView, View
)
from students.models import StudentsInfo
from institute_dashaboard.models import OnlineAdmission, complain
from django.urls import reverse_lazy
from django.contrib.auth.mixins import (
    LoginRequiredMixin, UserPassesTestMixin,
    PermissionRequiredMixin
)


class AssignClassesToTeacher(
    LoginRequiredMixin, UserPassesTestMixin,
    # PermissionRequiredMixin, 
    TemplateView
):
    template_name = 'assigned_class.html'
    # permission_required = 'dashboard_management.view_dashboard_management'

    def test_func(self):
        return self.request.user.is_active

dashboard_management/views/portal_management.py
from django.shortcuts import render, redirect
from django.views.generic import (
    ListView, CreateView, UpdateView, DetailView, TemplateView, View
)
from students.models import StudentsInfo
from institute_dashaboard.models import (
    OnlineAdmission, complain, Notice_board, News_headline, Gallery
)
from dashboard_management.forms import (
    NoticeBoardForm, NewsdForm, GalleryForm, TeacherForm,
    StuffForm
)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import (
    LoginRequiredMixin, UserPassesTestMixin,
    PermissionRequiredMixin
)
from django.shortcuts import get_object_or_404
from django.contrib import messages


class PortalManagerDashboard(
    LoginRequiredMixin, UserPassesTestMixin,
    PermissionRequiredMixin, 
    TemplateView
):
    template_name = 'portal_manager_dashboard.html'
    permission_required = 'dashboard_management.view_dashboard_management'

    def test_func(self):
        return self.request.user.is_active



class ADDNotice(
    LoginRequiredMixin, UserPassesTestMixin,
    # PermissionRequiredMixin,
      View
):
    template_name = 'add_notice.html'
    # permission_required = 'dashboard_management.view_dashboard_management'

    def test_func(self):
        return self.request.user.is_active
    
    def get(self, request):
        notice = Notice_board.objects.all()
        form = NoticeBoardForm()
        context = {
            'notice': notice,
            'form': form
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = NoticeBoardForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Notice uploaded successfully!')
            return redirect('dashboard_management:notice_adding')  # Adjust the URL to your routing
        notice = Notice_board.objects.all()
        context = {
            'notice': notice,
            'form': form
        }
        return render(request, self.template_name, context)


class DeleteNotice(View):
    def post(self, request, notice_id):
        notice = get_object_or_404(Notice_board, id=notice_id)
        notice.delete()
        messages.success(request, 'Notice deleted successfully!')
        return redirect('dashboard_management:notice_adding')  # Adjust the URL to your routing
    

class AddNews(
    LoginRequiredMixin, UserPassesTestMixin,
    # PermissionRequiredMixin,
      View
):
    template_name = 'add_news.html'
    # permission_required = 'dashboard_management.view_dashboard_management'

    def test_func(self):
        return self.request.user.is_active
    
    def get(self, request):
        notice = News_headline.objects.all()
        form = NewsdForm()
        context = {
            'notice': notice,
            'form': form
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = NewsdForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Notice uploaded successfully!')
            return redirect('dashboard_management:notice_adding')  # Adjust the URL to your routing
        notice = News_headline.objects.all()
        context = {
            'notice': notice,
            'form': form
        }
        return render(request, self.template_name, context)


class DeleteNews(View):
    def post(self, request, news_id):
        notice = get_object_or_404(News_headline, id=news_id)
        notice.delete()
        messages.success(request, 'News deleted successfully!')
        return redirect('dashboard_management:news_adding')  # Adjust the URL to your routing


class GalleryView(View):
    template_name = 'gallery_management.html'

    def get(self, request, gallery_id=None):
        if gallery_id:
            gallery = get_object_or_404(Gallery, id=gallery_id)
            form = GalleryForm(instance=gallery)
            action = 'edit'
        else:
            gallery = None
            form = GalleryForm()
            action = 'add'

        galleries = Gallery.objects.all()
        return render(request, self.template_name, {
            'form': form,
            'galleries': galleries,
            'action': action,
            'gallery': gallery,
        })

    def post(self, request, gallery_id=None):
        if gallery_id:
            gallery = get_object_or_404(Gallery, id=gallery_id)
            form = GalleryForm(request.POST, request.FILES, instance=gallery)
        else:
            form = GalleryForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            if gallery_id:
                messages.success(request, 'Photo updated successfully!')
            else:
                messages.success(request, 'Photo added successfully!')
            return redirect('dashboard_management:gallery_list')  # Adjust the URL as needed

        galleries = Gallery.objects.all()
        return render(request, self.template_name, {
            'form': form,
            'galleries': galleries,
            'action': 'edit' if gallery_id else 'add',
            'gallery': gallery if gallery_id else None,
        })

    def delete(self, request, gallery_id):
        gallery = get_object_or_404(Gallery, id=gallery_id)
        gallery.delete()
        messages.success(request, 'Photo deleted successfully!')
        return redirect('gallery_list')  # Adjust the URL as needed


class AddTeacherView(View):
    template_name = 'add_teacher.html'

    def get(self, request):
        form = TeacherForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = TeacherForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Teacher added successfully!')
            return redirect('teachers_info')  # Adjust the URL name as needed
        return render(request, self.template_name, {'form': form})


class AddStuff(View):
    template_name = 'add_stuff.html'

    def get(self, request):
        form = StuffForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = StuffForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Stuff added successfully!')
            return redirect('staf')  # Adjust the URL name as needed
        return render(request, self.template_name, {'form': form})

dashboard_management/templates/add_news.html
{% extends 'institute/base.html' %} 
{% load static %} 
{% load widget_tweaks %}
{% block title %}
<title>Students Dashboard</title>
{% endblock title %} 

<!-- left side main things start from here -->
{% block leftside %} 
<style>
    body{
        margin-top:20px;
        background:#FAFAFA;
    }
    .order-card {
        color: #fff;
    }
    
    .bg-c-blue {
        background: linear-gradient(45deg,#4099ff,#73b4ff);
    }
    
    .bg-c-green {
        background: linear-gradient(45deg,#2ed8b6,#59e0c5);
    }
    
    .bg-c-yellow {
        background: linear-gradient(45deg,#FFB64D,#ffcb80);
    }
    
    .bg-c-pink {
        background: linear-gradient(45deg,#FF5370,#ff869a);
    }
    
    
    .card {
        border-radius: 5px;
        -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);
        box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);
        border: none;
        margin-bottom: 30px;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out;
    }
    
    .card .card-block {
        padding: 25px;
    }
    
    .order-card i {
        font-size: 26px;
    }
    
    .f-left {
        float: left;
    }
    
    .f-right {
        float: right;
    }
</style>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Assigned Classes</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>


    <div class="container mt-5">
        <h2 class="text-center mb-4">Upload News Headline</h2>
    
        {% if messages %}
            <div class="mt-3">
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    
        <form method="post" enctype="multipart/form-data" class="mb-4">
            {% csrf_token %}
            
            <div class="mb-3">
                <label for="{{ form.title.id_for_label }}" class="form-label">Notice Title</label>
                {{ form.title|add_class:"form-control" }}
            </div>
        
            <div class="mb-3">
                <label for="{{ form.img_or_pdf.id_for_label }}" class="form-label">File/PDF</label>
                {{ form.img_or_pdf|add_class:"form-control" }}
            </div>
        
            <div class="mb-3">
                <label for="{{ form.notice_published_date.id_for_label }}" class="form-label">Published Date</label>
                {% comment %} {{ form.notice_published_date|add_class:"form-control"|type="date"}} {% endcomment %}
                {% render_field form.notice_published_date|add_class:"form-control" type="date" %}
            </div>
        
            <div class="mb-3">
                <label for="{{ form.url_link.id_for_label }}" class="form-label">URL Link</label>
                {{ form.url_link|add_class:"form-control" }}
            </div>
        
            <button type="submit" class="btn btn-primary">Upload Notice</button>
        </form>
        
    
        <h3 class="mt-5">Uploaded Notices</h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>File/PDF</th>
                    <th>Published Date</th>
                    <th>Link</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for item in notice %}
                    <tr>
                        <td>{{ item.title }}</td>
                        <td>
                            {% if item.img_or_pdf %}
                                <a href="{{ item.img_or_pdf.url }}" class="btn btn-link" target="_blank">Download</a>
                            {% else %}
                                <span class="text-muted">No file</span>
                            {% endif %}
                        </td>
                        <td>{{ item.notice_published_date }}</td>
                        <td>
                            {% if item.url_link %}
                                <a href="{{ item.url_link }}" class="btn btn-link" target="_blank">View Link</a>
                            {% else %}
                                <span class="text-muted">No link</span>
                            {% endif %}
                        </td>
                        <td>
                            
                            <form action="{% url 'dashboard_management:delete_news' item.id %}" method="POST" class="d-inline">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                            </form>
                        </td>
        
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4" class="text-center text-danger">No notices available.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

{% endblock leftside %}
{% block rightside %}

{% endblock rightside %}

dashboard_management/templates/add_notice.html
{% extends 'institute/base.html' %} 
{% load static %} 
{% load widget_tweaks %}
{% block title %}
<title>Students Dashboard</title>
{% endblock title %} 

<!-- left side main things start from here -->
{% block leftside %} 
<style>
    body{
        margin-top:20px;
        background:#FAFAFA;
    }
    .order-card {
        color: #fff;
    }
    
    .bg-c-blue {
        background: linear-gradient(45deg,#4099ff,#73b4ff);
    }
    
    .bg-c-green {
        background: linear-gradient(45deg,#2ed8b6,#59e0c5);
    }
    
    .bg-c-yellow {
        background: linear-gradient(45deg,#FFB64D,#ffcb80);
    }
    
    .bg-c-pink {
        background: linear-gradient(45deg,#FF5370,#ff869a);
    }
    
    
    .card {
        border-radius: 5px;
        -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);
        box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);
        border: none;
        margin-bottom: 30px;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out;
    }
    
    .card .card-block {
        padding: 25px;
    }
    
    .order-card i {
        font-size: 26px;
    }
    
    .f-left {
        float: left;
    }
    
    .f-right {
        float: right;
    }
</style>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Assigned Classes</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>


    <div class="container mt-5">
        <h2 class="text-center mb-4">Upload Notice</h2>
    
        {% if messages %}
            <div class="mt-3">
                {% for message in messages %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    
        <form method="post" enctype="multipart/form-data" class="mb-4">
            {% csrf_token %}
            
            <div class="mb-3">
                <label for="{{ form.title.id_for_label }}" class="form-label">Notice Title</label>
                {{ form.title|add_class:"form-control" }}
            </div>
        
            <div class="mb-3">
                <label for="{{ form.img_or_pdf.id_for_label }}" class="form-label">File/PDF</label>
                {{ form.img_or_pdf|add_class:"form-control" }}
            </div>
        
            <div class="mb-3">
                <label for="{{ form.notice_published_date.id_for_label }}" class="form-label">Published Date</label>
                {% comment %} {{ form.notice_published_date|add_class:"form-control"|type="date"}} {% endcomment %}
                {% render_field form.notice_published_date|add_class:"form-control" type="date" %}
            </div>
        
            <div class="mb-3">
                <label for="{{ form.url_link.id_for_label }}" class="form-label">URL Link</label>
                {{ form.url_link|add_class:"form-control" }}
            </div>
        
            <button type="submit" class="btn btn-primary">Upload Notice</button>
        </form>
        
    
        <h3 class="mt-5">Uploaded Notices</h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>File/PDF</th>
                    <th>Published Date</th>
                    <th>Link</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for item in notice %}
                    <tr>
                        <td>{{ item.title }}</td>
                        <td>
                            {% if item.img_or_pdf %}
                                <a href="{{ item.img_or_pdf.url }}" class="btn btn-link" target="_blank">Download</a>
                            {% else %}
                                <span class="text-muted">No file</span>
                            {% endif %}
                        </td>
                        <td>{{ item.notice_published_date }}</td>
                        <td>
                            {% if item.url_link %}
                                <a href="{{ item.url_link }}" class="btn btn-link" target="_blank">View Link</a>
                            {% else %}
                                <span class="text-muted">No link</span>
                            {% endif %}
                        </td>
                        <td>
                            <form action="{% url 'dashboard_management:delete_notice' item.id %}" method="POST" class="d-inline">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                            </form>
                        </td>
        
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4" class="text-center text-danger">No notices available.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

{% endblock leftside %}
{% block rightside %}

{% endblock rightside %}

dashboard_management/templates/portal_manager_dashboard.html
{% extends 'institute/base.html' %} 
{% load static %} 
{% load widget_tweaks %}
{% block title %}
<title>Students Dashboard</title>
{% endblock title %} 

<!-- left side main things start from here -->
{% block leftside %} 
<style>
    body{
        margin-top:20px;
        background:#FAFAFA;
    }
    .order-card {
        color: #fff;
    }
    
    .bg-c-blue {
        background: linear-gradient(45deg,#4099ff,#73b4ff);
    }
    
    .bg-c-green {
        background: linear-gradient(45deg,#2ed8b6,#59e0c5);
    }
    
    .bg-c-yellow {
        background: linear-gradient(45deg,#FFB64D,#ffcb80);
    }
    
    .bg-c-pink {
        background: linear-gradient(45deg,#FF5370,#ff869a);
    }
    
    
    .card {
        border-radius: 5px;
        -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);
        box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);
        border: none;
        margin-bottom: 30px;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out;
    }
    
    .card .card-block {
        padding: 25px;
    }
    
    .order-card i {
        font-size: 26px;
    }
    
    .f-left {
        float: left;
    }
    
    .f-right {
        float: right;
    }
</style>

<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" rel="stylesheet">
<div class="container-fluid">
    <div class="card">
        <div class="card-header">
            <p class="alert bg-success text-light text-center">Portal Manager Dashboard</p>
            <div class="card-body">
    <div class="row">
        <div class="col-md-4 col-xl-3">
            <a style="text-decoration:none"  href="{% url 'dashboard_management:add_teacher' %}"> 
                <div class="card bg-c-blue order-card">
                    <div class="card-block">
                        <h6 class="m-b-20">AT</h6>
                        <h4 class="text-right">Add Teacher</h4>
                        <p class="m-b-0">-</p>
                    </div>
                </div>
            </a>
        </div>
        
        <div class="col-md-4 col-xl-3">
            <a style="text-decoration:none"  href="{% url 'dashboard_management:add_stuff' %}"> 
                <div class="card bg-c-green order-card">
                <div class="card-block">
                    <h6 class="m-b-20">AS</h6>
                    <h4 class="text-right">Add Staff</h4>
                    <p class="m-b-0">-</span></p>
                </div>
            </div>
            </a>
        </div>
        
        <div class="col-md-4 col-xl-3">
            <a style="text-decoration:none"  href="{% url 'dashboard_management:notice_adding' %}"> 
            <div class="card bg-c-yellow order-card">
                <div class="card-block">
                    <h6 class="m-b-20">AN</h6>
                    <h4 class="text-right">Add Notice</span></h4>
                    <p class="m-b-0">-</span></p>
                </div>
            </div>
        </a>
        </div>
        <div class="col-md-4 col-xl-3">
            <a style="text-decoration:none"  href="{% url 'dashboard_management:news_adding' %}"> 
                <div class="card bg-c-yellow order-card">
                    <div class="card-block">
                        <h6 class="m-b-20">AN</h6>
                        <h4 class="text-right">Add News</span></h4>
                        <p class="m-b-0">-</span></p>
                    </div>
                </div>
            </a>
        </div>
        
        <div class="col-md-4 col-xl-3">
            <a style="text-decoration:none"  href="{% url 'dashboard_management:gallery_list' %}"> 
            <div class="card bg-c-pink order-card">
                <div class="card-block">
                    <h6 class="m-b-20">AG</h6>
                    <h4 class="text-right">Add Gallery</h4>
                    <p class="m-b-0">-</span></p>
                </div>
            </div>
        </a>
        </div>
        
        {% comment %} <div class="col-md-4 col-xl-3">
            <div class="card bg-c-pink order-card">
                <div class="card-block">
                    <h6 class="m-b-20">Result</h6>
                    <h2 class="text-right"><i class="fa-solid fa-screen-users"></i><span>486</span></h2>
                    <p class="m-b-0">Total<span class="f-right">351</span></p>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-xl-3">
            <div class="card bg-c-pink order-card">
                <div class="card-block">
                    <h6 class="m-b-20">Result</h6>
                    <h2 class="text-right"><i class="fa-solid fa-screen-users"></i><span>486</span></h2>
                    <p class="m-b-0">Total<span class="f-right">351</span></p>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-xl-3">
            <div class="card bg-c-pink order-card">
                <div class="card-block">
                    <h6 class="m-b-20">Result</h6>
                    <h2 class="text-right"><i class="fa-solid fa-screen-users"></i><span>486</span></h2>
                    <p class="m-b-0">Total<span class="f-right">351</span></p>
                </div>
            </div> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
	</div>
</div>
{% endblock leftside %}
{% block rightside %}

{% endblock rightside %}