CONFIG/urls.py
from pipes import Template
from django.contrib import admin
from django.urls import path, include
from institute_dashaboard import views
from django.conf import settings
from django.conf.urls.static import static
from Core.views import IndexView, SignupView, LoginView
from django.views.generic import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='homepage'),
    path('notice_board/', views.notice_board, name='notice_board'),
    # path('students_info/', views.students_info, name='students_info'),
    path('students_info/', views.StudentsInfoView.as_view(), name='students_info'),
    path('<int:id>/', views.students_details, name='students_details'),
    path('result/', views.result, name='result'),
    path('addmission/', views.OnlineAdmissionView.as_view(), name='onlineadm'),
    path('complain/', views.complain, name='complain'),
    path('contact/', views.contact_page, name='contact'),
    path('gallery/', views.gallery_page, name='gallery'),
    path('teachers_info/', views.teachers_page, name='teachers_info'),
    path('other_employee/', views.stafs_page, name='staf'),
    path('cultural_program/', views.cultur, name='cultur'),
    path('sports/', views.sports, name='sports'),
    path('speach/', views.speach, name='speach'),
    path('lokko_uddessho/', views.lokkouddessho, name='lokko'),
    path('history/', views.clg_history, name='history'),
    path('news/', views.newspage, name='news'),
    path('news/', views.newspage, name='news'),
    path('student/', include('students.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('auth/signup/', SignupView.as_view(), name='signup'),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('prms', include('django_prometheus.urls')),
    path('customize/', include('websitesetting.urls')),
    path('dashboard_management/', include('dashboard_management.urls')),
    

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Core/urls.py
"""Core > urls.py"""
# DJANGO URLS
from django.urls import path
# CORE IMPORTS
from Core import views

app_name = 'core'

urlpatterns = [
    # index url ---------------------------------------------------------------
    path('', views.IndexView.as_view(), name='index'),

    # user --------------------------------------------------------------------
    path(
        'users/', views.UserListView.as_view(), name='users'
    ),
    path(
        'user/create/', views.UserCreateView.as_view(), name='user_create'
    ),
    path(
        'user/detail/<int:pk>',
        views.UserDetailView.as_view(),
        name='user_detail'
    ),
    path(
        'user/update/<int:pk>',
        views.UserUpdateView.as_view(),
        name='user_update'
    ),
]

Core/forms/registration.py
"""Core > forms > registration.py"""
# DJANGO IMPORTS
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


USER_MODEL = get_user_model()


class SignupForm(UserCreationForm):
    """New user registration and signup form"""

    class Meta:
        """Meta class"""
        model = USER_MODEL
        fields = ('first_name', 'last_name', 'email', 'phone')

Core/forms/user.py
"""Core > forms > user.py"""
# DJANGO IMPORTS
from django import forms
from django.contrib.auth import get_user_model
# CORE IMPORTS
from Core.models import Profile


USER_MODEL = get_user_model()


class UserUpdateForm(forms.ModelForm):
    """User model form for create and update"""

    class Meta:
        """Meta class"""
        model = USER_MODEL
        fields = ('first_name', 'last_name', 'email', 'phone')


class ProfileUpdateForm(forms.ModelForm):
    """Profile model update form"""

    class Meta:
        """Meta class"""
        model = Profile
        exclude = ('user', 'is_active', 'created_at', 'last_updated')

Core/views/index.py
"""Core > views > index.py"""
# PYTHON IMPORTS
import logging
# DJANGO IMPORTS
from django.views.generic import TemplateView


logger = logging.getLogger(__name__)


class IndexView(TemplateView):
    """Landing page view"""
    template_name = 'index.html'

Core/views/registration.py
"""Core > views > index.py"""
# PYTHON IMPORTS
import logging
from sys import _getframe
# DJANGO IMPORTS
from django.contrib import messages
from django.contrib.auth import get_user_model, views
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.utils.translation import gettext_lazy as _
# CORE IMPORTS
from Core.forms import SignupForm


logger = logging.getLogger(__name__)
USER_MODEL = get_user_model()


# - LoginView, LogoutView used from django.contrib.auth.views
# - PasswordResetView sends the mail
# - PasswordResetDoneView shows a success message for the above
# - PasswordResetConfirmView checks clicked link and prompts for a new password
# - PasswordResetCompleteView shows a success message for the above


def redirect_auth_users(request, message=None):
    """Redirect authenticated users to index view"""
    logger.debug(  # prints function name and description
        f"{_getframe().f_code.co_name} "
        f"Redirecting {request.user} to IndexView..."
    )
    if not message:  # default message
        message = _(f"{request.user}, you are redirected to Index page.")
    messages.info(request=request, message=message)
    return redirect(reverse_lazy('students:dashobard_app'))


class SignupView(CreateView):
    """New user registration and signup view"""
    model = USER_MODEL
    form_class = SignupForm
    template_name = 'registration/signup.html'

    @staticmethod
    def get_redirect_message(request):
        """Returns a message to user when redirected"""
        return _(
            f"You are already registered as {request.user}. "
            f"Redirected you to Index page. "
            f"Please logout if you wish to create a new user."
        )

    def get(self, request, *args, **kwargs):
        """GET method"""
        logger.debug(  # prints class and function name
            f"{self.__class__.__name__}.{_getframe().f_code.co_name} "
            f"{request.user} is authenticated: {request.user.is_authenticated}"
        )
        # redirect authenticated users
        if request.user.is_authenticated:
            return redirect_auth_users(
                request=request, message=self.get_redirect_message(request)
            )

        # if user is not authenticated, proceed with SignupView
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        """POST method"""
        logger.debug(  # prints class and function name
            f"{self.__class__.__name__}.{_getframe().f_code.co_name} "
            f"Performing form validation..."
        )
        # redirect authenticated users
        if request.user.is_authenticated:
            return redirect_auth_users(
                request=request, message=self.get_redirect_message(request)
            )

        # if user is not authenticated, proceed with SignupView
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        """form is clean and validated"""
        logger.debug(  # prints class and function name
            f"{self.__class__.__name__}.{_getframe().f_code.co_name} "
            f"Form is clean and valid. Saving {form}"
        )
        self.object = form.save()
        self.object.refresh_from_db()  # creates profile instance via signals

        logger.debug(  # prints class and function name
            f"{self.__class__.__name__}.{_getframe().f_code.co_name} "
            f"User account was created for {self.object}."
        )
        message = _(
            f"{self.object}, your user account was created successfully. "
            f"Please login using your email address and password."
        )
        messages.success(request=self.request, message=message)
        return redirect(reverse_lazy('login'))

    def form_invalid(self, form):
        """form is invalid"""
        logger.debug(  # prints class and function name
            f"{self.__class__.__name__}.{_getframe().f_code.co_name} "
            f"Form is invalid. {form}"
        )
        logger.error(form.errors)  # log all form errors
        message = _("Validation error, please check all fields for any error.")
        messages.error(request=self.request, message=message)
        return super().form_invalid(form)


class LoginView(views.LoginView):
    """Overriding Django LoginView from django.contrib.auth.views"""

    @staticmethod
    def get_redirect_message(request):
        """Returns a message to user when redirected"""
        return _(
            f"You are already logged in as {request.user}. "
            f"Redirected you to Index page. "
            f"Please logout if you wish to log in as a new user."
        )

    def get(self, request, *args, **kwargs):
        """overriding GET method"""
        logger.debug(  # prints class and function name
            f"{self.__class__.__name__}.{_getframe().f_code.co_name} "
            f"{request.user} is authenticated: {request.user.is_authenticated}"
        )
        # redirect authenticated users
        if request.user.is_authenticated:
            return redirect_auth_users(
                request=request, message=self.get_redirect_message(request)
            )

        # if user is not authenticated, proceed with LoginView
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        """overriding POST method"""
        logger.debug(  # prints class and function name
            f"{self.__class__.__name__}.{_getframe().f_code.co_name} "
            f"Performing form validation..."
        )
        # redirect authenticated users
        if request.user.is_authenticated:
            return redirect_auth_users(
                request=request, message=self.get_redirect_message(request)
            )

        # if user is not authenticated, proceed with LoginView
        return super().post(request, *args, **kwargs)

Core/views/user.py
"""Core > views > user.py"""
# PYTHON IMPORTS
import logging
from sys import _getframe
# DJANGO IMPORTS
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import (
    UserPassesTestMixin, LoginRequiredMixin, PermissionRequiredMixin
)
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView
# CORE IMPORTS
from Core.forms import SignupForm, UserUpdateForm, ProfileUpdateForm
from Core.models import Profile
# PROJECT IMPORTS
from utils import test_user


logger = logging.getLogger(__name__)
USER_MODEL = get_user_model()


class UserListView(
    UserPassesTestMixin, LoginRequiredMixin, PermissionRequiredMixin,
    ListView
):
    """List view for User model"""
    model = USER_MODEL
    paginate_by = 100  # default
    ordering = ('id', )  # default; needed to avoid pagination inconsistency
    permission_required = 'Core.view_user'
    template_name = 'Core/user/list.html'

    def test_func(self):
        """Tests if user is_active and is_staff/is_superuser"""
        logger.debug(  # prints class and function name
            f"{self.__class__.__name__}.{_getframe().f_code.co_name} "
            f"Testing {self.request.user} status"
        )
        return test_user(self.request.user)


class UserDetailView(
    UserPassesTestMixin, LoginRequiredMixin, PermissionRequiredMixin,
    DetailView
):
    """Detail view for User model"""
    model = USER_MODEL
    permission_required = ('Core.view_user', 'Core.view_profile')
    template_name = 'Core/user/detail.html'

    def test_func(self):
        """Tests if user is_active and is_staff/is_superuser"""
        logger.debug(  # prints class and function name
            f"{self.__class__.__name__}.{_getframe().f_code.co_name} "
            f"Testing {self.request.user} status"
        )
        obj = self.get_object()

        # tests if the user is the same as the object he is trying to view
        is_owner = (obj == self.request.user) and self.request.user.is_active

        return is_owner or test_user(self.request.user)


class UserCreateView(
    UserPassesTestMixin, LoginRequiredMixin, PermissionRequiredMixin,
    CreateView
):
    """Create view for user model"""
    model = USER_MODEL
    form_class = SignupForm
    permission_required = 'Core.add_user'
    template_name = 'Core/user/create.html'

    def test_func(self):
        """Tests if user is_active and is_staff/is_superuser"""
        logger.debug(  # prints class and function name
            f"{self.__class__.__name__}.{_getframe().f_code.co_name} "
            f"Testing {self.request.user} status"
        )
        return test_user(self.request.user)

    def get_success_url(self):
        """Overriding to redirect to detail view"""
        url = reverse_lazy('core:user_detail', kwargs={'pk': self.object.pk})
        logger.debug(  # prints class and function name
            f"{self.__class__.__name__}.{_getframe().f_code.co_name} "
            f"Generated success url: {url}"
        )
        return url


class UserUpdateView(
    UserPassesTestMixin, LoginRequiredMixin, PermissionRequiredMixin,
    UpdateView
):
    """Update view for user model. Can also be used as detail view"""
    model = USER_MODEL
    form_class = UserUpdateForm
    form2_class = ProfileUpdateForm
    permission_required = ('Core.change_user', 'Core.change_profile')
    template_name = 'Core/user/update.html'

    def test_func(self):
        """Tests if user is_active and is_staff/is_superuser"""
        logger.debug(  # prints class and function name
            f"{self.__class__.__name__}.{_getframe().f_code.co_name} "
            f"Testing {self.request.user} status"
        )
        obj = self.get_object()

        # tests if the user is the same as the object he is trying to update
        is_owner = (obj == self.request.user) and self.request.user.is_active

        # tests if user instance is_staff/is_superuser, then staff not allowed
        staff_allowed = True
        if obj.is_staff or obj.is_superuser:
            staff_allowed = False

        # tests for is_superuser and is_active
        is_superuser = self.request.user.is_superuser and \
            self.request.user.is_active

        return is_owner or staff_allowed or is_superuser

    def get_form2_kwargs(self):
        """Copies get_form_kwargs() to include profile form kwargs"""
        logger.debug(  # prints class and function name
            f"{self.__class__.__name__}.{_getframe().f_code.co_name} "
            f"Getting profile form keyword arguments..."
        )

        kwargs = self.get_form_kwargs()
        kwargs.update({
            'instance': Profile.objects.get(user=self.get_object())
        })
        return kwargs

    def get_context_data(self, **kwargs):
        """Overriding to include profile form and extra data"""
        logger.debug(  # prints class and function name
            f"{self.__class__.__name__}.{_getframe().f_code.co_name} "
            f"Getting context data..."
        )

        if 'form2' not in kwargs:
            kwargs['form2'] = self.form2_class(**self.get_form2_kwargs())
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        """Overriding post method to include profile form validation"""
        logger.debug(  # prints class and function name
            f"{self.__class__.__name__}.{_getframe().f_code.co_name} "
            f"POST form data for user: {request.user}"
        )

        self.object = self.get_object()
        form = self.get_form()  # user form
        form2 = self.form2_class(**self.get_form2_kwargs())  # profile form

        if form.is_valid() and form2.is_valid():
            form2.save()  # saves profile object
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self):
        """Overriding to redirect to detail view"""
        url = reverse_lazy('core:user_detail', kwargs={'pk': self.object.pk})
        logger.debug(  # prints class and function name
            f"{self.__class__.__name__}.{_getframe().f_code.co_name} "
            f"Generated success url: {url}"
        )
        return url

Core/templates/Core/user/create.html
{% comment %} {% extends 'base/base.html' %} {% endcomment %}
{% load static widget_tweaks %}

{% block title_text %}Create | User{% endblock %}
{% block content_heading_text %}Create User{% endblock %}

{% block crumbs_items %}
    <li class="breadcrumb-item" aria-current="page">
        <a href="{% url 'core:users' %}">USERS</a>
    </li>
    <li class="breadcrumb-item" aria-current="page">
        <a href="{% url 'core:user_create' %}">CREATE</a>
    </li>
{% endblock %}

{% block content %}
    <div class="row no-gutters content-border my-1 p-3">
        {% if perms.Core.add_user %}
            {% if form %}
                <form class="container-fluid" method="POST" accept-charset="UTF-8">
                    {% csrf_token %}
                    {% include 'snippets/hidden_fields.html' %}

                    <!-- first_name -->
                    <div class="form-row border bg-light py-1">
                        <div class="col-4 my-auto">{{ form.first_name.label }} :</div>
                        <div class="col-8">{% include 'snippets/input_field.html' with form=form formfld=form.first_name placeholder=form.first_name.label icon='fas fa-id-card' %}</div>
                    </div>

                    <!-- last_name -->
                    <div class="form-row border py-1">
                        <div class="col-4 my-auto">{{ form.last_name.label }} :</div>
                        <div class="col-8">{% include 'snippets/input_field.html' with form=form formfld=form.last_name placeholder=form.last_name.label icon='far fa-id-card' %}</div>
                    </div>

                    <!-- email -->
                    <div class="form-row border bg-light py-1">
                        <div class="col-4 my-auto">{{ form.email.label }} :</div>
                        <div class="col-8">{% include 'snippets/input_field.html' with form=form formfld=form.email placeholder=form.email.label icon='fas fa-at' %}</div>
                    </div>

                    <!-- phone -->
                    <div class="form-row border py-1">
                        <div class="col-4 my-auto">{{ form.phone.label }} :</div>
                        <div class="col-8">{% include 'snippets/input_field.html' with form=form formfld=form.phone placeholder=form.phone.label icon='fas fa-mobile-alt' %}</div>
                    </div>

                    <!-- password1 -->
                    <div class="form-row border bg-light p-1">
                        <div class="col-4 my-auto">{{ form.password1.label }} :</div>
                        <div class="col-8">{% include 'snippets/passwd_field.html' with form=form formfld=form.password1 placeholder=form.password1.label icon='fas fa-key' %}</div>
                    </div>

                    <!-- password2 -->
                    <div class="form-row border p-1">
                        <div class="col-4 my-auto">{{ form.password2.label }} :</div>
                        <div class="col-8">{% include 'snippets/passwd_field.html' with form=form formfld=form.password2 placeholder=form.password2.label icon='fas fa-lock' %}</div>
                    </div>

                    <!-- button -->
                    <button id='loader' class="btn btn-sm btn-outline-info font-saira w-100 mt-2" type="button" hidden><i class="fa fa-spinner fa-spin mr-1"></i>CREATING...</button>
                    <button id='submit' class="btn btn-sm btn-info font-saira w-100 mt-2" type="submit"><i class="fas fa-user-plus mr-1"></i>CREATE USER</button>
                </form>
            {% else %}
                No form found.
            {% endif %}
        {% else %}
            User, you do not have permissions to create a new user.
        {% endif %}
    </div>
{% endblock %}

{% block js_extra %}
    <script src="{% static 'js/passwd_show.js' %}"></script>
    <script src="{% static 'js/btn_loader.js' %}"></script>
{% endblock %}

Core/templates/Core/user/detail.html
{% comment %} {% extends 'base/base.html' %} {% endcomment %}
{% load static widget_tweaks %}

{% block title_text %}Detail | User{% endblock %}
{% block content_heading_text %}User Detail{% endblock %}

{% block crumbs_items %}
    <li class="breadcrumb-item" aria-current="page">
        <a href="{% url 'core:users' %}">USERS</a>
    </li>
    <li class="breadcrumb-item" aria-current="page">
        <a href="{% url 'core:user_detail' object.pk %}">DETAIL</a>
    </li>
{% endblock %}

{% block content %}
    <div class="row no-gutters content-border my-1 p-3">
        {% if perms.Core.view_user and perms.Core.view_profile %}
            {% if object %}
                <div class="container-fluid">
                    <!-- ID -->
                    <div class="row border py-1">
                        <div class="col-4 my-auto">ID :</div>
                        <div class="col-8"><i class="fas fa-hashtag pr-1"></i>{{ object.id }}</div>
                    </div>

                    <!-- first_name -->
                    <div class="row border bg-light py-1">
                        <div class="col-4 my-auto">First name :</div>
                        <div class="col-8"><i class="fas fa-id-card pr-1"></i>{{ object.first_name }}</div>
                    </div>

                    <!-- last_name -->
                    <div class="row border py-1">
                        <div class="col-4 my-auto">Family name :</div>
                        <div class="col-8"><i class="far fa-id-card pr-1"></i>{{ object.last_name }}</div>
                    </div>

                    <!-- email -->
                    <div class="row border bg-light py-1">
                        <div class="col-4 my-auto">Email address :</div>
                        <div class="col-8"><i class="fas fa-at pr-1"></i>{{ object.email }}</div>
                    </div>

                    <!-- phone -->
                    <div class="row border py-1">
                        <div class="col-4 my-auto">Mobile phone :</div>
                        <div class="col-8"><i class="fas fa-mobile-alt pr-1"></i>{{ object.phone }}</div>
                    </div>

                    <!-- date_joined -->
                    <div class="row border bg-light py-1">
                        <div class="col-4 my-auto">Date Joined :</div>
                        <div class="col-8"><i class="fas fa-calendar-day pr-1"></i>{{ object.date_joined }}</div>
                    </div>

                    <!-- last_updated -->
                    <div class="row border py-1">
                        <div class="col-4 my-auto">Last Updated :</div>
                        <div class="col-8"><i class="fas fa-calendar pr-1"></i>{{ object.last_updated }}</div>
                    </div>

                    <!-- last_login -->
                    <div class="row border bg-light py-1">
                        <div class="col-4 my-auto">Last Login :</div>
                        <div class="col-8"><i class="fas fa-calendar-check pr-1"></i>{{ object.last_login }}</div>
                    </div>

                    <!-- PROFILE -->
                    <div class="row text-light font-weight-bold font-saira bg-info border mt-4 mb-2 px-2 py-1"><h3 class="text-center mb-0">Profile</h3></div>

                    <!-- image -->
                    {% comment %}
                    <div class="row border py-1">
                        <div class="col-4 my-auto">Profile picture :</div>
                        <div class="col-8">{% object.image %}</div>
                    </div>
                    {% endcomment %}

                    <!-- bio -->
                    <div class="row border bg-light py-1">
                        <div class="col-4 my-auto">Bio :</div>
                        <div class="col-8"><i class="fas fa-file-alt pr-1"></i>{{ object.profile.bio }}</div>
                    </div>

                    <!-- birthday -->
                    <div class="row border py-1">
                        <div class="col-4 my-auto">Birthday :</div>
                        <div class="col-8"><i class="fas fa-birthday-cake pr-1"></i>{{ object.profile.birthday }}</div>
                    </div>

                    <!-- gender -->
                    <div class="row border bg-light py-1">
                        <div class="col-4 my-auto">Gender :</div>
                        <div class="col-8"><i class="fas fa-restroom pr-1"></i>{{ object.profile.gender }}</div>
                    </div>

                    <!-- spouse_name -->
                    <div class="row border py-1">
                        <div class="col-4 my-auto">Spouse name :</div>
                        <div class="col-8"><i class="fas fa-user-friends pr-1"></i>{{ object.profile.spouse_name }}</div>
                    </div>

                    <!-- father_name -->
                    <div class="row border bg-light py-1">
                        <div class="col-4 my-auto">Father name :</div>
                        <div class="col-8"><i class="fas fa-users pr-1"></i>{{ object.profile.father_name }}</div>
                    </div>

                    <!-- mother_name -->
                    <div class="row border py-1">
                        <div class="col-4 my-auto">Mother name :</div>
                        <div class="col-8"><i class="fas fa-users pr-1"></i>{{ object.profile.mother_name }}</div>
                    </div>

                    <!-- nid -->
                    <div class="row border bg-light py-1">
                        <div class="col-4 my-auto">National ID :</div>
                        <div class="col-8"><i class="fas fa-id-card pr-1"></i>{{ object.profile.nid }}</div>
                    </div>

                    <!-- passport -->
                    <div class="row border py-1">
                        <div class="col-4 my-auto">Passport :</div>
                        <div class="col-8"><i class="fas fa-passport pr-1"></i>{{ object.profile.passport }}</div>
                    </div>
                </div>

                <!-- update -->
                {% if perms.Core.change_user and perms.Core.change_profile %}
                    <a class="row no-gutters text-decoration-none mt-3 w-100" href="{% url 'core:user_update' pk=object.pk %}">
                        <button class="btn btn-sm btn-info font-saira w-100" type="button">UPDATE DETAILS</button>
                    </a>
                {% endif %}
            {% else %}
                No record found.
            {% endif %}
        {% else %}
            User, you do not have permissions to view this content.
        {% endif %}
    </div>
{% endblock %}

Core/templates/Core/user/list.html
{% comment %} {% extends 'base/base.html' %} {% endcomment %}

{% block title_text %}List | User{% endblock %}
{% block content_heading_text %}User's List{% endblock %}

{% block crumbs_items %}
    <li class="breadcrumb-item" aria-current="page">
        <a href="{% url 'core:users' %}">USERS</a>
    </li>
{% endblock %}

{% block content %}
    {% if perms.Core.add_user %}
        <div class="row no-gutters content-border bg-info my-1">
            <a class="w-100" href="{% url 'core:user_create' %}">
                <button class="btn btn-info font-saira w-100" type="button"><i class="fas fa-user-plus pr-1"></i>CREATE NEW USER</button>
            </a>
        </div>
    {% endif %}

    <div class="row no-gutters content-border">
        {% if perms.Core.view_user %}
            {% if object_list %}
                <!-- table header -->
                <div class="row no-gutters border font-saira text-info bg-dark text-truncate w-100 p-1">
                    <div class="col-auto text-truncate pl-2 pr-1" style="min-width: 60px;" title="ID">ID</div>
                    <div class="col-2 text-truncate px-1" style="min-width: 100px;" title="FULL NAME">NAME</div>
                    <div class="col font-weight-bold text-truncate px-1" style="min-width: 120px;" title="EMAIL ADDRESS">EMAIL</div>
                    <div class="col-auto text-truncate px-1" style="min-width: 120px;" title="PHONE NUMBER">PHONE</div>
                    <div class="col-auto d-none d-md-block text-truncate px-1" style="min-width: 150px;" title="LAST LOGIN DATETIME">LAST LOGIN</div>
                    <div class="col-auto d-none d-md-block text-truncate px-1" style="width: 24px;" title="ACTIVE STATUS">ACTIVE</div>
                    <div class="col-auto d-none d-md-block text-truncate px-1" style="width: 24px;" title="STAFF STATUS">STAFF</div>
                    <div class="col-auto d-none d-md-block text-truncate px-1" style="width: 24px;" title="SUPERUSER STATUS">SUPERUSER</div>
                </div>

                <!-- table data -->
                {% for obj in object_list %}
                <div class="row no-gutters border text-truncate w-100 p-1{% if forloop.counter0|divisibleby:2 %} bg-light{% endif %}">
                    <div class="col-auto text-truncate pl-2 pr-1" style="min-width: 60px;" title="{{ obj.id }}"><a class="text-decoration-none" href="{% url 'core:user_detail' pk=obj.pk %}">{{ obj.id }}</a></div>
                    <div class="col-2 text-truncate px-1" style="min-width: 100px;" title="{{ obj.get_full_name }}">{{ obj.get_full_name }}</div>
                    <div class="col font-weight-bold text-truncate px-1" style="min-width: 120px;" title="{{ obj.email }}"><a class="text-decoration-none" href="{% url 'core:user_detail' pk=obj.pk %}">{{ obj.email }}</a></div>
                    <div class="col-auto text-truncate px-1" style="min-width: 120px;" title="{{ obj.phone }}">{{ obj.phone }}</div>
                    <div class="col-auto d-none d-md-block text-truncate px-1" style="min-width: 150px;" title="{{ obj.last_login }}">{{ obj.last_login|date:"y/m/d h:iA" }}</div>
                    <div class="col-auto d-none d-md-block text-truncate px-1" style="width: 24px;" title="ACTIVE STATUS: {{ obj.is_active }}">
                        {% if obj.is_active %}<i class="fas fa-check-circle text-success"></i>{% else %}<i class="fas fa-times-circle text-danger"></i>{% endif %}
                    </div>
                    <div class="col-auto d-none d-md-block text-truncate px-1" style="width: 24px;" title="STAFF STATUS: {{ obj.is_staff }}">
                        {% if obj.is_staff %}<i class="fas fa-check-circle text-success"></i>{% else %}<i class="fas fa-times-circle text-danger"></i>{% endif %}
                    </div>
                    <div class="col-auto d-none d-md-block text-truncate px-1" style="width: 24px;" title="SUPERUSER STATUS: {{ obj.is_superuser }}">
                        {% if obj.is_superuser %}<i class="fas fa-check-circle text-success"></i>{% else %}<i class="fas fa-times-circle text-danger"></i>{% endif %}
                    </div>
                </div>
                {% endfor %}

                <!-- Pagination -->
                {% include 'snippets/pagination.html' %}
            {% else %}
                No records found.
            {% endif %}
        {% else %}
            User, you do not have permissions to view this content.
        {% endif %}
    </div>
{% endblock %}